// Edge Function — generate-pdf
//
// Contract (blocker doc §3.4, stage-4 §4.1):
//   POST { prospect_id, template_kind, fields? }
//   -> { document: { id, storage_path, sha256, page_count, status } }
//
// Storage path: documents/{tenant_id}/documents/{prospect_id}/{doc_id}-unsigned.pdf
//
// This is a minimal but correct implementation: it enforces auth, role,
// tenant scoping, writes a real PDF (placeholder body) via pdf-lib, and
// inserts the `documents` row. Template prose comes in a follow-up PR
// per stage-4 §4.4 (legal text owned by the product owner).

import { serve } from 'https://deno.land/std@0.177.0/http/server.ts'
import { PDFDocument, StandardFonts, rgb } from 'https://esm.sh/pdf-lib@1.17.1'

import {
  corsHeaders,
  getAuthedUser,
  jsonError,
  jsonOk,
  preflight,
} from '../_shared/auth.ts'

type TemplateKind = '3rd_party_auth' | 'acv_contract' | 'rcv_contract' | 'supplement'

const ALLOWED_KINDS: TemplateKind[] = [
  '3rd_party_auth',
  'acv_contract',
  'rcv_contract',
  'supplement',
]

const ALLOWED_ROLES = ['telefonista', 'admin', 'owner', 'super_admin']

const TEMPLATE_TITLES: Record<TemplateKind, string> = {
  '3rd_party_auth': '3rd Party Authorization',
  acv_contract: 'ACV Contract',
  rcv_contract: 'RCV Contract',
  supplement: 'Supplement Document',
}

async function sha256Hex(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', bytes)
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
}

serve(async (req) => {
  if (req.method === 'OPTIONS') return preflight()
  if (req.method !== 'POST') return jsonError(405, 'method_not_allowed')

  const authed = await getAuthedUser(req)
  if ('error' in authed) return authed.error
  const { user, supabase } = authed

  if (!ALLOWED_ROLES.includes(user.role)) {
    return jsonError(403, 'forbidden', `Role ${user.role} cannot generate documents`)
  }

  let input: {
    prospect_id?: string
    template_kind?: TemplateKind
    fields?: Record<string, unknown>
  }
  try {
    input = await req.json()
  } catch {
    return jsonError(400, 'invalid_json')
  }

  if (!input.prospect_id) return jsonError(400, 'missing_prospect_id')
  if (!input.template_kind || !ALLOWED_KINDS.includes(input.template_kind)) {
    return jsonError(400, 'invalid_template_kind')
  }

  // 1. Load prospect; verify tenant.
  const { data: prospect, error: pErr } = await supabase
    .from('prospects')
    .select('id, tenant_id, name, address, city, state, zip, phones, email')
    .eq('id', input.prospect_id)
    .single()
  if (pErr || !prospect) return jsonError(404, 'prospect_not_found')
  if (prospect.tenant_id !== user.tenant_id && user.role !== 'super_admin') {
    return jsonError(403, 'forbidden', 'Cross-tenant access denied')
  }

  // 2. Pre-create the documents row so we have an id for the storage path.
  const { data: doc, error: dErr } = await supabase
    .from('documents')
    .insert({
      tenant_id: prospect.tenant_id,
      prospect_id: prospect.id,
      type: input.template_kind,
      status: 'generated',
      created_by: user.id,
    })
    .select('id')
    .single()
  if (dErr || !doc) return jsonError(500, 'db_insert_failed', dErr?.message)

  // 3. Render a minimal PDF. Real legal templates land in a follow-up
  //    per stage-4 §4.4 — the contract here is the bytes + storage path,
  //    not the prose.
  const pdf = await PDFDocument.create()
  const page = pdf.addPage([612, 792])
  const helv = await pdf.embedFont(StandardFonts.Helvetica)
  const helvBold = await pdf.embedFont(StandardFonts.HelveticaBold)

  page.drawRectangle({
    x: 0,
    y: 732,
    width: 612,
    height: 60,
    color: rgb(0xe8 / 0xff, 0x50 / 0xff, 0x1f / 0xff),
  })
  page.drawText(TEMPLATE_TITLES[input.template_kind], {
    x: 40,
    y: 752,
    size: 18,
    font: helvBold,
    color: rgb(1, 1, 1),
  })

  const lines = [
    `Homeowner: ${prospect.name}`,
    `Address: ${[prospect.address, prospect.city, prospect.state, prospect.zip]
      .filter(Boolean)
      .join(', ')}`,
    `Phone: ${prospect.phones?.[0] ?? '—'}`,
    `Email: ${prospect.email ?? '—'}`,
    '',
    'This document is a placeholder generated by Roof-Aid CRM.',
    'Final legal text will be supplied by the product owner before launch.',
  ]
  let y = 700
  for (const line of lines) {
    page.drawText(line, { x: 40, y, size: 11, font: helv })
    y -= 18
  }

  // Signature marker — embed-signature scans for this.
  const sigY = 120
  page.drawLine({
    start: { x: 60, y: sigY },
    end: { x: 320, y: sigY },
    thickness: 1,
    color: rgb(0, 0, 0),
  })
  page.drawText('Homeowner signature', { x: 60, y: sigY - 14, size: 8, font: helv })
  page.drawText(`<<sig:home:60,${sigY}>>`, {
    x: 0,
    y: 0,
    size: 0.001,
    color: rgb(1, 1, 1),
    font: helv,
  })

  page.drawText('Electronically generated via Roof-Aid CRM', {
    x: 40,
    y: 30,
    size: 8,
    font: helv,
    color: rgb(0.4, 0.4, 0.4),
  })

  const bytes = await pdf.save()
  const sha256 = await sha256Hex(bytes)
  const storagePath = `${prospect.tenant_id}/documents/${prospect.id}/${doc.id}-unsigned.pdf`

  const { error: uErr } = await supabase.storage
    .from('documents')
    .upload(storagePath, bytes, {
      contentType: 'application/pdf',
      upsert: false,
    })
  if (uErr) {
    await supabase.from('documents').delete().eq('id', doc.id)
    return jsonError(500, 'storage_upload_failed', uErr.message)
  }

  await supabase
    .from('documents')
    .update({ storage_path: storagePath })
    .eq('id', doc.id)

  return jsonOk({
    document: {
      id: doc.id,
      storage_path: storagePath,
      sha256,
      page_count: pdf.getPageCount(),
      status: 'generated',
    },
  })
})

// Re-export to silence "unused" warnings during linting.
export { corsHeaders }
